FROM nvidia/cudagl:10.0-devel-ubuntu18.04
MAINTAINER Sukrit Kalra (sukrit.kalra@berkeley.edu)

# Set up a erdos user first.
RUN apt-get -y update && apt-get -y install sudo
ENV uid 1000
ENV gid 1000

RUN mkdir -p /home/erdos
RUN groupadd erdos -g ${gid} 
RUN useradd -r -u ${uid} -g erdos erdos
RUN echo "erdos ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/erdos
RUN chmod 0440 /etc/sudoers.d/erdos
RUN chown ${uid}:${gid} -R /home/erdos


USER erdos
ENV HOME /home/erdos
ENV SHELL /bin/bash
WORKDIR /home/erdos

RUN mkdir -p /home/erdos/workspace
RUN cd /home/erdos/workspace

# Set up the pylot code.
RUN sudo apt-get install -y python-pip
RUN pip install gdown

# Retrieve CARLA
RUN sudo apt-get -y update && sudo apt-get -y install wget
RUN cd /home/erdos/workspace/ && wget http://carla-assets-internal.s3.amazonaws.com/Releases/Linux/CARLA_0.9.6.tar.gz
RUN cd /home/erdos/workspace/ && mkdir -p CARLA_0.9.6 && mv CARLA_0.9.6.tar.gz CARLA_0.9.6/
RUN cd /home/erdos/workspace/CARLA_0.9.6 && tar xvf CARLA_0.9.6.tar.gz && rm -rf CARLA_0.9.6.tar.gz
ENV SDL_VIDEODRIVER offscreen
ENV CARLA_HOME /home/erdos/workspace/CARLA_0.9.6
