FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
MAINTAINER Sukrit Kalra (sukrit.kalra@berkeley.edu)

# Set up a erdos user first.
RUN apt-get -y update && apt-get -y install sudo
ENV uid 1000
ENV gid 1000

RUN mkdir -p /home/erdos
RUN groupadd erdos -g ${gid} 
RUN useradd -r -u ${uid} -g erdos erdos
RUN echo "erdos ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/erdos
RUN chmod 0440 /etc/sudoers.d/erdos
RUN chown ${uid}:${gid} -R /home/erdos


USER erdos
ENV HOME /home/erdos
ENV SHELL /bin/bash
WORKDIR /home/erdos
SHELL ["/bin/bash", "-c"]

# Get the erdos directory.
RUN sudo apt-get -y update
RUN sudo apt-get -y install git curl clang python3 python3-pip
RUN pip3 install setuptools setuptools-rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/home/erdos/.cargo/bin:${PATH}"
RUN rustup default nightly
RUN mkdir -p /home/erdos/workspace
RUN cd /home/erdos/workspace && git clone https://github.com/erdos-project/erdos.git

# Install Tensorflow
RUN pip3 install tensorflow-gpu==1.13.1

# Get the Pylot directory.
RUN cd /home/erdos/workspace && git clone https://github.com/erdos-project/pylot.git
WORKDIR /home/erdos/workspace/pylot/
# Get the Pylot models and code dependencies.
RUN sudo apt-get install -y wget
RUN cd /home/erdos/workspace/pylot/ && ./install.sh docker
# Install all the Python dependencies.
RUN cd /home/erdos/workspace/pylot/ && pip3 install -e ./

# Set this env value to run carla in headless CARLA
ENV SDL_VIDEODRIVER offscreen
# Install ssh in order to be able to forward X for Carla visualization.
RUN sudo apt-get -y install ssh

# Export PYTHONPATH
RUN echo "export PYTHONPATH=/home/erdos/workspace/pylot/dependencies/:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.6/PythonAPI/carla/dist/carla-0.9.6-py3.5-linux-x86_64.egg:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.6/PythonAPI/carla/" >> ~/.bashrc

RUN echo "export CARLA_0_9_5=/home/erdos/workspace/pylot/dependencies/:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.5/PythonAPI/carla/dist/carla-0.9.5-py3.5-linux-x86_64.egg:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.5/PythonAPI/carla/" >> ~/.bashrc

RUN echo "export CARLA_0_9_7=/home/erdos/workspace/pylot/dependencies/:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.7/PythonAPI/carla/dist/carla-0.9.7-py3.5-linux-x86_64.egg:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.7/PythonAPI/carla/" >> ~/.bashrc

# Expose the required ports.
EXPOSE 2000 2001 2002
