name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-python:
    name: "Python ${{ matrix.python-version }} Build"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7]
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install -r tests/requirements.txt
          python -m pip install yapf flake8

      - name: Check Python formatting
        run: |
          yapf --diff --recursive ./pylot/
          yapf --diff ./pylot.py
          yapf --diff ./lincoln.py
          yapf --diff ./data_gatherer.py
          flake8 ./pylot/
          flake8 ./pylot.py
          flake8 ./lincoln.py
          flake8 ./data_gatherer.py

      - name: Run tests
        run: |
          python -m pytest tests/
