name: Documentation
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  pythondoc:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Python dependencies
        run: python -m pip install -r doc/requirements-doc.txt


      - name: Build Documentation
        run: |
          cd doc
          make html
